# Utilisez l'image nginx comme base
FROM nginx:latest

# Copiez tout le contenu du répertoire de construction dans le répertoire HTML de Nginx
COPY . /usr/share/nginx/html

# Exposez le port 80 pour accéder au service
EXPOSE 80
